# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: beatprojectagent

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- name: Install gnupg
  apt:
    name: gnupg2
    state: present
    update_cache: yes

- name: Install ELK APT Repo Signing Key
  apt_key:
    url: "{{ ELK_APT_REPO_KEY }}"
    state: present

- name: Install ELK 8.x APT Repo 
  apt_repository:
    repo: "{{ ELK_8_APT_REPO }}"
    state: present

- name: Update Repo cache and install Filebeat
  apt:
    name: filebeat=8.5.2
    update_cache: yes
